'use strict';
const assets={library:'assets/large_beidaihe1_1_5797a0dcbc.webp',chapel:'assets/large_beidaihe11_1_d8756e62cf.webp',aerial:'assets/large_beidaihe2_1_e62b546aa1.webp',coast:'coast.webp'};
const scenes=[{image:assets.coast,alt:'阿那亚海岸沙滩航拍',caption:'到达的第一天，先安顿。',route:['北京','园区入口','住处','就近晚餐'],spots:[['小镇生活圈','找到吃饭、休息和回家的路','阿那亚四期小镇广场']]},{image:assets.library,alt:'孤独图书馆面向大海的建筑外观',caption:'给第一次来的人，一张海边合影。',route:['住处','礼堂外观','图书馆外观','回房午休'],spots:[['阿那亚礼堂','海边合影，外观短停','阿那亚礼堂'],['孤独图书馆','看建筑与海，室内需另查预约','阿那亚孤独图书馆']]},{image:assets.chapel,alt:'阿那亚礼堂晚霞中的外观',caption:'音乐与社区，把节日过慢一点。',route:['音乐会可选','附近短逛','回房午休','北岸可选'],spots:[['礼堂清晨音乐会','08:20可选，宝宝不入场','阿那亚礼堂'],['北岸滨河生活','足球短时观看，跨区先查接驳','阿那亚北岸ANAR FC滨河足球场']]},{image:assets.coast,alt:'阿那亚沙滩与海浪航拍，非海钓实拍',caption:'大人有半天自由，宝宝照常午睡。',route:['早餐交接','夫妻出海','老人宝宝留园','午后团聚'],spots:[['海钓码头候选','以实际订单确定码头，尚未订船','南戴河葡萄岛码头']]},{image:assets.aerial,alt:'阿那亚孤独图书馆建筑俯瞰',caption:'再看一眼海，吃过午饭回家。',route:['早餐收拾','11点前退房','午餐','午后返京'],spots:[['熟悉的小镇','上午不跨区，午饭后返京','阿那亚四期小镇广场']]}];
let selected=0;let activeView='journey';const panel=document.getElementById('day-panel'),tabs=[...document.querySelectorAll('[data-day]')],weather=document.getElementById('weather');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pin='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M20 10c0 6-8 11-8 11S4 16 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>';
const mapURL=place=>'https://uri.amap.com/search?'+new URLSearchParams({keyword:place,city:'秦皇岛',view:'map',src:'aranya-family-guide',callnative:'1'});
const mapLink=(place,label='高德查看地点')=>'<a class="map-link" href="'+esc(mapURL(place))+'" target="_blank" rel="noopener">'+pin+esc(label)+'</a>';
function wireMaps(root=document){root.querySelectorAll('[data-map]').forEach(a=>{a.href=mapURL(a.dataset.map);a.target='_blank';a.rel='noopener'})}
function render(){const d=days[selected],s=scenes[selected];tabs.forEach((b,i)=>{b.setAttribute('aria-selected',String(i===selected));b.tabIndex=i===selected?0:-1});panel.setAttribute('aria-labelledby','tab-'+selected);
 panel.innerHTML='<article class="day-feature"><figure><img src="'+s.image+'" alt="'+esc(s.alt)+'" width="1080" height="720"><figcaption>'+esc(s.caption)+'</figcaption></figure><div class="day-intro"><div class="date-line">'+esc(d.date)+'<span>节奏轻松</span></div><h2>'+esc(d.title)+'</h2><p>'+esc(d.summary)+'</p><div class="day-rhythm"><span>'+(selected===0?'抵达后 · 吃饭与安顿':'11:30左右 · 午餐')+'</span><span>'+(selected===4?'午饭后 · 返京':selected===0?'按状态 · 休息':'12:30—14:30 · 午休')+'</span></div></div></article><div class="route-block"><h3>今天的路线</h3><ol class="route-line">'+(weather.checked?(selected===4?['早餐收拾','退房寄存','午餐','午后返京']:selected===0?['北京','园区入口','就近吃饭','入住休息']:['住处','就近午餐','回房午休','室内短停']):s.route).map((x,i)=>'<li><span class="route-dot">'+(i+1)+'</span><span>'+esc(x)+'</span></li>').join('')+'</ol></div><div class="daily-grid"><div class="daily-main"><div class="subheading"><h3>'+(weather.checked?'风大 / 下雨，这样安排':'按这个节奏走')+'</h3><span>时间为建议，可随作息调整</span></div>'+(weather.checked?'<div class="weather-plan"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M6 15a4 4 0 0 1-1-8 6 6 0 0 1 11-2 5 5 0 0 1 2 10M8 18l-1 3m6-3-1 3m6-3-1 3"/></svg><p>'+esc(d.rain)+'</p></div>':'<ol class="timeline">'+d.slots.map((slot,i)=>'<li class="'+(slot[1].includes('午休')?'nap':'')+'"><div class="time">'+esc(slot[0])+'</div><details '+((i===0||slot[1].includes('退房'))?'open':'')+'><summary>'+esc(slot[1])+'</summary><p>'+esc(slot[2])+'</p></details></li>').join('')+'</ol>')+'<div class="day-tip"><strong>记住这一件事</strong><p>'+esc(d.tip)+'</p></div></div><aside class="daily-side"><h3>今天去哪儿</h3><div class="spot-list">'+(weather.checked?[]:s.spots).map(x=>'<article><h4>'+esc(x[0])+'</h4><p>'+esc(x[1])+'</p>'+mapLink(x[2])+'</article>').join('')+(weather.checked?'<p class="rain-spots">今天以住处和熟悉的餐厅为中心，取消户外地点与码头安排。</p>':'')+'</div><h3>每个人的安排</h3><div class="people">'+['爷爷奶奶','宝宝','夫妻'].map((n,i)=>'<div><h4>'+n+'</h4><p>'+esc(weather.checked?['住处附近休息，取消户外久留；7日午饭后返京。','保持吃饭和午睡节奏，不去码头和草坪等候。','确认天气、停航与退改，安排就近用餐和陪护。'][i]:d.people[i])+'</p></div>').join('')+'</div></aside></div>';
}
function switchView(name,scroll=true){activeView=name;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==name);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));history.replaceState(null,'','#'+name);if(scroll)document.getElementById(name).scrollIntoView({behavior:'auto',block:'start'});}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();switchView('journey')});
tabs.forEach((b,i)=>{b.addEventListener('click',()=>{selected=i;render()});b.addEventListener('keydown',e=>{let j=i;if(e.key==='ArrowRight')j=(i+1)%tabs.length;else if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;else if(e.key==='Home')j=0;else if(e.key==='End')j=tabs.length-1;else return;e.preventDefault();selected=j;render();tabs[j].focus()})});weather.addEventListener('change',render);
let storageOK=true;function storeValue(key,value){try{localStorage.setItem(key,value)}catch{storageOK=false}}function readValue(key){try{return localStorage.getItem(key)}catch{return null}}
function setLarge(large){document.body.classList.toggle('large',large);const b=document.getElementById('large');b.setAttribute('aria-pressed',String(large));b.textContent=large?'标准字号':'大字模式'}
setLarge(readValue('aranya-large')==='true');document.getElementById('large').addEventListener('click',()=>{const large=!document.body.classList.contains('large');setLarge(large);storeValue('aranya-large',String(large))});
document.getElementById('rain-switch').addEventListener('click',()=>{weather.checked=true;render();switchView('journey');weather.focus({preventScroll:true})});
const zones=[{title:'住处附近',note:'抵达先认路，出海日老人宝宝留在这里',image:assets.coast,alt:'阿那亚海岸实景，非民宿房间照片',places:[['四期小镇广场','按家人口述暂定四期，实际分期待核实'],['第三食堂','用餐候选，先确认营业与身份码'],['第四食堂','用餐候选，以实际住处距离为准']]},{title:'经典海边',note:'礼堂与图书馆外观，看海合影就足够',image:assets.library,alt:'阿那亚孤独图书馆外观',places:[['礼堂','音乐会预约，1.2米以下谢绝入场'],['孤独图书馆','外观可作路线，室内另查预约'],['湿地公园','先确认适合推车的短线']]},{title:'北岸社区',note:'跨区先查接驳，一次选一个主要活动',image:null,alt:'',places:[['北岸雀跃镇','故事会与草坪活动区域'],['北岸ANAR FC滨河足球场','3—5日14:00—18:00可观赛'],['北岸Andmore','Kayak活动，成人备选']]}];
document.getElementById('place-grid').innerHTML=zones.map(z=>'<article class="zone">'+(z.image?'<figure><img src="'+z.image+'" alt="'+z.alt+'" loading="lazy" width="1080" height="720"></figure>':'<div class="zone-sign"><span>北岸</span><p>故事会 / 草坪 / 足球 / Kayak</p></div>')+'<div class="zone-content"><h3>'+z.title+'</h3><p class="muted">'+z.note+'</p>'+z.places.map(x=>'<div class="place-row"><div><h4>'+x[0]+'</h4><p>'+x[1]+'</p></div>'+mapLink('阿那亚'+x[0],'高德地图')+'</div>').join('')+'</div></article>').join('');
const filters=[document.getElementById('event-date'),document.getElementById('event-person')];function filterEvents(){const date=filters[0].value,person=filters[1].value;let n=0;document.querySelectorAll('.event').forEach(e=>{e.hidden=!(date==='all'||e.dataset.dates.split(' ').includes(date))||!(person==='all'||e.dataset.person===person);if(!e.hidden)n++});document.getElementById('event-count').textContent=n?n+'个活动候选 · 时间以截图为依据，余位请查App':'这个组合暂无活动候选，可以换日期或查看全部人群。'}filters.forEach(f=>f.addEventListener('change',filterEvents));filterEvents();
const items=['宝宝：奶与辅食、尿布、湿巾、换洗衣物','宝宝：推车、背带、薄毯与防风外套','老人：日常用品、舒适鞋、手机充电器','住宿：确认分期、楼栋入口、停车和寄存','活动：在阿那亚App确认场次、入场规则与余位','海钓：确认码头、船型、费用和天气退改','回程：11点前退房，午饭后取行李返京'];document.getElementById('checklist').innerHTML=items.map((s,i)=>'<label class="check-row"><input type="checkbox" data-check="'+i+'" '+(readValue('aranya-check-'+i)==='true'?'checked':'')+'><span>'+s+'</span></label>').join('');document.querySelectorAll('[data-check]').forEach(x=>x.addEventListener('change',()=>{storeValue('aranya-check-'+x.dataset.check,String(x.checked));if(!storageOK)toast('浏览器未允许保存，勾选仅在本次页面有效。')}));
let toastTimer;function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3500)}
document.getElementById('share').addEventListener('click',async()=>{const u=location.origin+location.pathname;try{await navigator.clipboard.writeText(u);toast('分享链接已复制，可以发给家人。')}catch{toast('无法自动复制，请复制浏览器地址分享。')}});
wireMaps();const now=new Date();if(now.getFullYear()===2026&&now.getMonth()===9&&now.getDate()>=3&&now.getDate()<=7)selected=now.getDate()-3;render();const initial=location.hash.slice(1);if(document.getElementById(initial)?.classList.contains('view'))switchView(initial,false);
